exclude: [TheOneYouDontLike.github.io.sublime-project, TheOneYouDontLike.github.io.sublime-workspace, Gemfile, Gemfile.lock]
permalink: /post/:title
url: aimforsimplicity.com
disqusid: aimforsimplicitycom
title: aimforsimplicity.com
description: Personal opinions about software development.
author: Krzysztof Jendrzyca
excerpt_separator: <!--more-->