exclude: [Gemfile, Gemfile.lock]
permalink: /post/:title/
url: aimforsimplicity.com
# disqusid: aimforsimplicitycom
# title: aimforsimplicity.com
description: Strive for simplicity in software development.
author: Krzysztof Jendrzyca
twitter_username: kjendrzyca
excerpt_separator: --
markdown: kramdown
kramdown:
  input: GFM
