exclude: [TheOneYouDontLike.github.io.sublime-project, TheOneYouDontLike.github.io.sublime-workspace, Gemfile, Gemfile.lock]
permalink: /post/:title
url: http://theoneyoudontlike.github.io
disqusid: theoneyoudontlike
title: The One You Don't Like
description: Personal opinions about software development.
author: The One You Don't Like